metrics:
  wal_directory: /etc/agent/data
  global:
    scrape_interval: 15s
    remote_write:
      - url: http://mimir:9009/api/v1/push
  
  configs:
    - name: grafana
      scrape_configs:
        - job_name: grafana
          static_configs:
            - targets: ['grafana:3000']
              #      remote_write:
              #- url: http://mimir:9009/api/v1/push
              
integrations:
