apiVersion: policy/v1 
kind: PodDisruptionBudget
metadata:
  name: grafana-pdb
spec:
  minAvailable: 1  # Ensures at least 1 Grafana pod remains available
  selector:
    matchLabels:
      app: grafana
