apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce # Adjust based on storage provider
  storageClassName: standard  # Replace if not using the default 
  resources:
    requests:
      storage: 2Gi 

